### ISSUE TITLE
new LCN version descriptor (descriptor_tag == 0x82) used by provider NOS at 30W

### ISSUE THREAD

**Issue by Azureit** [oe-alliance/AutoBouquetsMaker#233]
At 30W provider NOS use a different LCN version descriptor (descriptor_tag == 0x82).
It's the same thing as the normal LCN (descriptor_tag == 0x83) but without the visible_service_flag and my guess is when logical_channel_number=0 it's to mark an old service to be removed.

The relevant part of the NIT table with my annotations I used to confirm with an official receiver:
```
    Transport_stream_ID: 47 (0x002f)
    Original_network_ID: 54 (0x0036)  [= TV Cabo | TV Cabo Portugal]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 201 (0x00c9)

            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 90 (0x5a)
               service_ID: 4 (0x0004)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 5 (0x0005)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 6 (0x0006)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 18 (0x0012)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 317 (0x013d)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 700 (0x02bc)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 701 (0x02bd)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 800 (0x0320)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 804 (0x0324)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 807 (0x0327)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 808 (0x0328)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 809 (0x0329)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 815 (0x032f)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 816 (0x0330)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 818 (0x0332)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 822 (0x0336)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 825 (0x0339)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 826 (0x033a)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 827 (0x033b)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 828 (0x033c)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 829 (0x033d)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 947 (0x03b3)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 1298 (0x0512)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 1305 (0x0519)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 1306 (0x051a)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 1338 (0x053a)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 1340 (0x053c)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 1341 (0x053d)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 1342 (0x053e)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 36861 (0x8ffd)[ --> refers to PMT program_number]
               service_type: 141 (0x8d)  [= User defined]


            DVB-DescriptorTag: 67 (0x43)  [= satellite_delivery_system_descriptor]
            descriptor_length: 11 (0x0b)
            Frequency: 19150612 (=  12.43714 GHz)
            Orbital_position: 768 (=  30.0)
            West_East_flag: 0 (0x00)  [= WEST]
            Polarisation: 0 (0x00)  [= linear - horizontal]
            Kind: 1 (0x01)  [= DVB-S2]
            Roll Off Faktor: 2 (0x02)  [= Alpha 0.20]
            Modulation_type: 2 (0x02)  [= 8PSK]
            Symbol_rate: 2576384 (=  27.5000)
            FEC_inner: 3 (0x03)  [= 3/4 conv. code rate]

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 8 (0x00000008)  [= TV Cabo Portugal]

            DVB-DescriptorTag: 130 (0x82)  [= User defined/ATSC reserved]
            descriptor_length: 88 (0x58)
            Descriptor-data:
                | SID | LCN |
                 00 99 00 00 --> service_id=153, ??? (ignore)
                 00 9a 00 00 --> service_id=154, ??? (ignore)
                 01 3d 00 64 --> service_id=317, logical_channel_number=100, Discovery Channel
                 01 ce 00 00 --> service_id=462, ??? (ignore)
                 03 20 01 1a --> service_id=800, logical_channel_number=282, TSF (radio)
                 03 24 00 4e --> service_id=804, logical_channel_number=78, TV Cine Action HD
                 03 27 00 a0 --> service_id=807, logical_channel_number=160, Trace Toca
                 03 28 00 29 --> service_id=808, logical_channel_number=41, Nickelodeon
                 03 29 00 84 --> service_id=809, logical_channel_number=132, Fuel TV
                 03 2f 00 8e --> service_id=815, logical_channel_number=142, Caça & Pesca
                 03 30 00 2e --> service_id=816, logical_channel_number=46, Nick Jr.
                 03 32 00 73 --> service_id=818, logical_channel_number=115, Discovery HD
                 03 36 00 28 --> service_id=822, logical_channel_number=40, Disney Channel
                 03 39 00 aa --> service_id=825, logical_channel_number=170, Globo Now
                 03 b3 00 4b --> service_id=947, logical_channel_number=75, TV Cine Top HD
                 05 12 00 54 --> service_id=1298, logical_channel_number=84, AMC HD
                 05 19 00 3d --> service_id=1305, logical_channel_number=61, AMC
                 05 1a 00 86 --> service_id=1306, logical_channel_number=134, Motorvision
                 05 3a 00 0b --> service_id=1338, logical_channel_number=11, Canal 11 HD
                 05 3c 00 7d --> service_id=1340, logical_channel_number=125, ZAP Viva HD
                 05 3d 00 10 --> service_id=1341, logical_channel_number=16, NOS Studios HD
                 05 3e 00 51 --> service_id=1342, logical_channel_number=81, NOS Studios
```
___________________________________
```
    Transport_stream_ID: 101 (0x0065)
    Original_network_ID: 83 (0x0053)  [= PT Comunicações | PT Comunicações]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 243 (0x00f3)

            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 96 (0x60)
               service_ID: 151 (0x0097)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 152 (0x0098)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 153 (0x0099)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 154 (0x009a)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 155 (0x009b)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 156 (0x009c)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 157 (0x009d)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 158 (0x009e)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 159 (0x009f)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 160 (0x00a0)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 161 (0x00a1)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 162 (0x00a2)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 163 (0x00a3)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 164 (0x00a4)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 165 (0x00a5)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 166 (0x00a6)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 167 (0x00a7)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 168 (0x00a8)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 169 (0x00a9)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]

               service_ID: 170 (0x00aa)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 171 (0x00ab)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 172 (0x00ac)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 173 (0x00ad)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 174 (0x00ae)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 175 (0x00af)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 176 (0x00b0)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 177 (0x00b1)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 178 (0x00b2)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 179 (0x00b3)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 180 (0x00b4)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 181 (0x00b5)[ --> refers to PMT program_number]
               service_type: 2 (0x02)  [= digital radio sound service]

               service_ID: 199 (0x00c7)[ --> refers to PMT program_number]
               service_type: 1 (0x01)  [= digital television service]


            DVB-DescriptorTag: 67 (0x43)  [= satellite_delivery_system_descriptor]
            descriptor_length: 11 (0x0b)
            Frequency: 18952230 (=  12.13026 GHz)
            Orbital_position: 768 (=  30.0)
            West_East_flag: 0 (0x00)  [= WEST]
            Polarisation: 0 (0x00)  [= linear - horizontal]
            Kind: 1 (0x01)  [= DVB-S2]
            Roll Off Faktor: 2 (0x02)  [= Alpha 0.20]
            Modulation_type: 2 (0x02)  [= 8PSK]
            Symbol_rate: 2576384 (=  27.5000)
            FEC_inner: 3 (0x03)  [= 3/4 conv. code rate]

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 8 (0x00000008)  [= TV Cabo Portugal]

            DVB-DescriptorTag: 130 (0x82)  [= User defined/ATSC reserved]
            descriptor_length: 124 (0x7c)
            Descriptor-data:
                | SID | LCN |
                 00 97 00 01 --> service_id=151, logical_channel_number=1, RTP 1 HD
                 00 98 00 02 --> service_id=152, logical_channel_number=2, RTP 2 HD
                 00 99 00 03 --> service_id=153, logical_channel_number=3, SIC HD
                 00 9a 00 04 --> service_id=154, logical_channel_number=4, TVI HD
                 00 9b 00 06 --> service_id=155, logical_channel_number=6, RTP 3
                 00 9c 00 07 --> service_id=156, logical_channel_number=7, CNN Portugal
                 00 9d 00 08 --> service_id=157, logical_channel_number=8, CM TV
                 00 9e 00 0a --> service_id=158, logical_channel_number=9, Globo
                 00 9f 00 1c --> service_id=159, logical_channel_number=28, Porto Canal
                 00 a0 00 30 --> service_id=160, logical_channel_number=48, SIC Kids
                 00 a1 00 2f --> service_id=161, logical_channel_number=47, Baby TV
                 00 a2 00 70 --> service_id=162, logical_channel_number=112, Canal História
                 00 a3 00 12 --> service_id=163, logical_channel_number=18, RTP Memoria
                 00 a4 00 48 --> service_id=164, logical_channel_number=72, MTV Portugal
                 00 a5 00 db --> service_id=165, logical_channel_number=219, ARTV
                 00 a6 00 be --> service_id=166, logical_channel_number=190, RTP Africa
                 00 a7 00 bd --> service_id=167, logical_channel_number=219, RTP Açores
                 00 a8 00 bc --> service_id=168, logical_channel_number=188, RTP Madeira
                 00 a9 00 49 --> service_id=169, logical_channel_number=73, TV Record
                 00 aa 01 09 --> service_id=170, logical_channel_number=265, Antena 1 (radio)
                 00 ab 01 0a --> service_id=171, logical_channel_number=266, Antena 2 (radio)
                 00 ac 01 0b --> service_id=172, logical_channel_number=267, Antena 3 (radio)
                 00 ad 01 0c --> service_id=173, logical_channel_number=268, RDP África (radio)
                 00 ae 01 0d --> service_id=174, logical_channel_number=269, Rádio Lusitánia (radio)
                 00 af 01 0f --> service_id=175, logical_channel_number=271, Cidade FM (radio)
                 00 b0 01 11 --> service_id=176, logical_channel_number=273, Smooth FM (radio) 
                 00 b1 01 18 --> service_id=177, logical_channel_number=280, RFM (radio)
                 00 b2 01 13 --> service_id=178, logical_channel_number=275, Mega Hits (radio)
                 00 b3 01 19 --> service_id=179, logical_channel_number=281, Renascença (radio)
                 00 b4 01 10 --> service_id=180, logical_channel_number=272, Rádio Comercial (radio)
                 00 b5 01 12 --> service_id=181, logical_channel_number=274, M80 (radio)

```
