### ISSUE TITLE
Canal Digital Nordic - error in Norwegian and Finnish channellist

### ISSUE THREAD

**Issue by bobben1no** [oe-alliance/AutoBouquetsMaker#4]
The Norwegian and Finnish channel list is not generated correctly by AutoBouquetsMaker.  Box is Xtrend ET10000 with latest openPLI and "about" says it is version 2.4 of AutoBouquetsMaker.

Norwegian HD and Norwegian SD seems to be a mix of Norwegian and Swedish channels.  Finnish HD and Finnish SD seems to be a mix of Finnish,Swedish and Norwegian channels.

I tested Danish and Swedish lists and they seem to be correct according to http://www.satellite-calculations.com/Satellite/DVB_frequency_lists.htm

**Comment by AbuBaniaz** [comment]
Can you post more workable details please?

**Comment by McLalala** [comment]
HD STB channel list
Swedish: http://www.satellite-calculations.com/DVB/1west/printlist.php?lcn/1/snr/-99/all/Swedish_Nordig_Channel_List.htm?MPEG4
Norwegian: http://www.satellite-calculations.com/DVB/1west/printlist.php?lcn/1/snr/-99/all/Norwegian_Nordig_Channel_List.htm?MPEG4
Danish: http://www.satellite-calculations.com/DVB/1west/printlist.php?lcn/1/snr/-99/all/Danish_Nordig_Channel_List.htm?MPEG4
Finnish: http://www.satellite-calculations.com/DVB/1west/printlist.php?lcn/1/snr/-99/all/Finnish_Nordig_Channel_List.htm?MPEG4

All of them updated daily, I think. :)

**Comment by AbuBaniaz** [comment]
The list to compare with must be an official list from the provider. Or pictures from the official receiver showing the channel order.

**Comment by ngjermundshaug** [comment]
Still an issue.

**Comment by AbuBaniaz** [comment]
Can you please provide an official list by the broadcaster/provider

**Comment by ngjermundshaug** [comment]
Yes - see here: https://www.satellite-calculations.com/DVB/getchannellist.php?1west/Norwegian_Nordig_Channel_List.htm

(It's dynamically updated)

**Comment by AbuBaniaz** [comment]
Official provider please, not a third party website. If that is not possible, clear pictures from official receiver please

**Comment by ngjermundshaug** [comment]
Official channel list - which you will see correspond to the previous page: 
https://tvguide.canaldigital.no

PS! The number 4 is skipped on 
https://www.satellite-calculations.com/DVB/getchannellist.php?1west/Norwegian_Nordig_Channel_List.htm for some reason.

**Comment by ngjermundshaug** [comment]
https://satellitt.canaldigital.no/contentassets/b67996692405474e92ce76c7f8ae52db/oppdatert-kanalliste.pdf

**Comment by Huevos** [comment]
What satellite is this, 1W or 4.8E? I think it is beyond my reach.

**Comment by ngjermundshaug** [comment]
It is 1w

**Comment by ngjermundshaug** [comment]
How's it going? Let me know if you need anything else!

**Comment by AbuBaniaz** [comment]
Do you use skype?

**Comment by AbuBaniaz** [comment]
Please accept the invitation

**Comment by AbuBaniaz** [comment]
For anyone else wanting to get this corrected....
Unzip and transfer the attached file to your HDD
ChMod 755 the folder and sub directories

Telnet to your receiver and install dvbsnoop with

'''opkg install dvbsnoop'''

Change directory to where the dvbstream file is for your receiver

'''cd /media/hdd/dvbstream/mips'''

or

'''cd /media/hdd/dvbstream/arm'''

On your receiver select the frequency you want to record
For example, Canal Digital on 1 west uses the following home frequency: frequency="12418000" symbol_rate="28000000" Vertical
Ensure no other recordings are taking place or are due to take place

Issue the following command

'''
./dvbstream `dvbsnoop -s pidscan| awk '/PID found/ { print $3 }' | xargs` -o>1w_12418.ts
'''

Stop with 'Ctrl' & 'C'

We only need about a minutes worth of recording. Upload the file for us to inspect

The file was by Athoik using some work by Dave Chapman. Does not work on all receivers

[dvbstream athoik 2017-05-24.zip](https://github.com/oe-alliance/AutoBouquetsMaker/files/2814418/dvbstream.athoik.2017-05-24.zip)

**Comment by ngjermundshaug** [comment]
/media/hdd only contains 1 file: **epg.dat.loading**

Unable to find any file names dvbstream on the tuner 

Running VU+ Zero - BlsckHole 3.0.8C (2019-04-17)

**Comment by Huevos** [comment]
/media/hdd only contains 1 file: epg.dat.loading
That has nothing to do with ABM

_Unable to find any file names dvbstream on the tuner_
You have to load them yourself. If it is a Vu+ those files probably won't work

**Comment by ngjermundshaug** [comment]
I am at the location (my cabin) with the VU+ now - so I played around with dvbsnoop.

dvbsnoop -nph works ok:

```

root@vuzero:~# dvbsnoop -n 1  -nph 0x10
dvbsnoop V1.4.53 -- https://github.com/PLi-metas/dvbsnoop 


SECT-Packet: 00000001   PID: 16 (0x0010), Length: 846 (0x034e)
Time received: Tue 2021-12-28  22:19:34.604

PID:  16 (0x0010)  [= assigned for: DVB Network Information Table (NIT), Stuffing Table (ST)]

Guess table from table id...
NIT-decoding....
Table_ID: 64 (0x40)  [= Network Information Table (NIT) - actual network]
section_syntax_indicator: 1 (0x01)
reserved_1: 1 (0x01)
reserved_2: 3 (0x03)
Section_length: 843 (0x034b)
Network_ID: 70 (0x0046)  [= >>ERROR: not (yet) defined... Report!<<]
reserved_3: 3 (0x03)
Version_number: 14 (0x0e)
current_next_indicator: 1 (0x01)  [= valid now]
Section_number: 6 (0x06)
Last_Section_number: 8 (0x08)
reserved_4: 15 (0x0f)
Network_descriptor_length: 10 (0x000a)

        DVB-DescriptorTag: 64 (0x40)  [= network_name_descriptor]
        descriptor_length: 8 (0x08)
        Network_name: "Telenor"  -- Charset: Latin alphabet no. 5


reserved_5: 15 (0x0f)
Transport_stream_loop_length: 820 (0x0334)

    Transport_stream_ID: 65 (0x0041)
    Original_network_ID: 70 (0x0046)  [= 1 degree W | Telenor]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 113 (0x0071)

            DVB-DescriptorTag: 67 (0x43)  [= satellite_delivery_system_descriptor]
            descriptor_length: 11 (0x0b)
            Frequency: 17303808 (=  10.80900 GHz)
            Orbital_position: 16 (=   1.0)
            West_East_flag: 0 (0x00)  [= WEST]
            Polarisation: 0 (0x00)  [= linear - horizontal]
            Kind: 1 (0x01)  [= DVB-S2]
            Roll Off Faktor: 1 (0x01)  [= Alpha 0.25]
            Modulation_type: 2 (0x02)  [= 8PSK]
            Symbol_rate: 2424832 (=  25.0000)
            FEC_inner: 3 (0x03)  [= 3/4 conv. code rate]

            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 0 (0x00)

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 17 (0x11)
            Descriptor-data:
                 0000:  01 0b 4c 43 4e 20 44 65  6e 6d 61 72 6b 44 4e 4b   ..LCN DenmarkDNK
                 0010:  00                                                 .

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 17 (0x11)
            Descriptor-data:
                 0000:  02 0b 4c 43 4e 20 46 69  6e 6c 61 6e 64 46 49 4e   ..LCN FinlandFIN
                 0010:  00                                                 .

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 16 (0x10)
            Descriptor-data:
                 0000:  03 0a 4c 43 4e 20 4e 6f  72 77 61 79 4e 4f 52 00   ..LCN NorwayNOR.

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 16 (0x10)
            Descriptor-data:
                 0000:  04 0a 4c 43 4e 20 53 77  65 64 65 6e 53 57 45 00   ..LCN SwedenSWE.


    Transport_stream_ID: 66 (0x0042)
    Original_network_ID: 70 (0x0046)  [= 1 degree W | Telenor]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 167 (0x00a7)

            DVB-DescriptorTag: 67 (0x43)  [= satellite_delivery_system_descriptor]
            descriptor_length: 11 (0x0b)
            Frequency: 17266688 (=  10.77800 GHz)
            Orbital_position: 16 (=   1.0)
            West_East_flag: 0 (0x00)  [= WEST]
            Polarisation: 0 (0x00)  [= linear - horizontal]
            Kind: 1 (0x01)  [= DVB-S2]
            Roll Off Faktor: 1 (0x01)  [= Alpha 0.25]
            Modulation_type: 2 (0x02)  [= 8PSK]
            Symbol_rate: 2424832 (=  25.0000)
            FEC_inner: 3 (0x03)  [= 3/4 conv. code rate]

            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 18 (0x12)
               service_ID: 7030 (0x1b76)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7268 (0x1c64)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7270 (0x1c66)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7442 (0x1d12)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7443 (0x1d13)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7444 (0x1d14)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]


            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 21 (0x15)
            Descriptor-data:
                 0000:  01 0b 4c 43 4e 20 44 65  6e 6d 61 72 6b 44 4e 4b   ..LCN DenmarkDNK
                 0010:  04 1b 76 fc 68                                     ..v.h

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 21 (0x15)
            Descriptor-data:
                 0000:  02 0b 4c 43 4e 20 46 69  6e 6c 61 6e 64 46 49 4e   ..LCN FinlandFIN
                 0010:  04 1b 76 fc 23                                     ..v.#

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 20 (0x14)
            Descriptor-data:
                 0000:  03 0a 4c 43 4e 20 4e 6f  72 77 61 79 4e 4f 52 04   ..LCN NorwayNOR.
                 0010:  1b 76 fc 67                                        .v.g

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 40 (0x28)
            Descriptor-data:
                 0000:  04 0a 4c 43 4e 20 53 77  65 64 65 6e 53 57 45 18   ..LCN SwedenSWE.
                 0010:  1c 64 fc 4d 1d 14 fc 53  1d 13 fc 52 1d 12 fc 51   .d.M...S...R...Q
                 0020:  1b 76 fc 36 1c 66 fc 46                            .v.6.f.F


    Transport_stream_ID: 67 (0x0043)
    Original_network_ID: 70 (0x0046)  [= 1 degree W | Telenor]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 211 (0x00d3)

            DVB-DescriptorTag: 67 (0x43)  [= satellite_delivery_system_descriptor]
            descriptor_length: 11 (0x0b)
            Frequency: 17266688 (=  10.77800 GHz)
            Orbital_position: 16 (=   1.0)
            West_East_flag: 0 (0x00)  [= WEST]
            Polarisation: 1 (0x01)  [= linear - vertical]
            Kind: 1 (0x01)  [= DVB-S2]
            Roll Off Faktor: 1 (0x01)  [= Alpha 0.25]
            Modulation_type: 2 (0x02)  [= 8PSK]
            Symbol_rate: 2424832 (=  25.0000)
            FEC_inner: 3 (0x03)  [= 3/4 conv. code rate]

            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 42 (0x2a)
               service_ID: 1061 (0x0425)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 2924 (0x0b6c)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 4103 (0x1007)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 4807 (0x12c7)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 6801 (0x1a91)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7160 (0x1bf8)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 11061 (0x2b35)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 14103 (0x3717)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 17924 (0x4604)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 18004 (0x4654)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 18006 (0x4656)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 18011 (0x465b)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 18024 (0x4668)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 18055 (0x4687)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]


            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 33 (0x21)
            Descriptor-data:
                 0000:  01 0b 4c 43 4e 20 44 65  6e 6d 61 72 6b 44 4e 4b   ..LCN DenmarkDNK
                 0010:  10 12 c7 fc 06 0b 6c fc  05 46 54 fd 2e 46 04 fc   ......l..FT..F..
                 0020:  82                                                 .

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 17 (0x11)
            Descriptor-data:
                 0000:  02 0b 4c 43 4e 20 46 69  6e 6c 61 6e 64 46 49 4e   ..LCN FinlandFIN
                 0010:  00                                                 .

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 32 (0x20)
            Descriptor-data:
                 0000:  03 0a 4c 43 4e 20 4e 6f  72 77 61 79 4e 4f 52 10   ..LCN NorwayNOR.
                 0010:  37 17 fd 2d 04 25 fc 08  10 07 fc 06 2b 35 fd 2e   7..-.%......+5..

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 40 (0x28)
            Descriptor-data:
                 0000:  04 0a 4c 43 4e 20 53 77  65 64 65 6e 53 57 45 18   ..LCN SwedenSWE.
                 0010:  1b f8 fc 09 1a 91 fc 05  46 5b fc 94 46 56 fc 93   ........F[..FV..
                 0020:  46 68 fc 8a 46 87 fc 88                            Fh..F...


    Transport_stream_ID: 68 (0x0044)
    Original_network_ID: 70 (0x0046)  [= 1 degree W | Telenor]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 176 (0x00b0)

            DVB-DescriptorTag: 67 (0x43)  [= satellite_delivery_system_descriptor]
            descriptor_length: 11 (0x0b)
            Frequency: 17254144 (=  10.74700 GHz)
            Orbital_position: 16 (=   1.0)
            West_East_flag: 0 (0x00)  [= WEST]
            Polarisation: 0 (0x00)  [= linear - horizontal]
            Kind: 1 (0x01)  [= DVB-S2]
            Roll Off Faktor: 1 (0x01)  [= Alpha 0.25]
            Modulation_type: 2 (0x02)  [= 8PSK]
            Symbol_rate: 2424832 (=  25.0000)
            FEC_inner: 3 (0x03)  [= 3/4 conv. code rate]

            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 27 (0x1b)
               service_ID: 1034 (0x040a)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 1035 (0x040b)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 6404 (0x1904)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7065 (0x1b99)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7069 (0x1b9d)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7073 (0x1ba1)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7078 (0x1ba6)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7148 (0x1bec)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 17073 (0x42b1)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]


            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 17 (0x11)
            Descriptor-data:
                 0000:  01 0b 4c 43 4e 20 44 65  6e 6d 61 72 6b 44 4e 4b   ..LCN DenmarkDNK
                 0010:  00                                                 .

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 17 (0x11)
            Descriptor-data:
                 0000:  02 0b 4c 43 4e 20 46 69  6e 6c 61 6e 64 46 49 4e   ..LCN FinlandFIN
                 0010:  00                                                 .

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 52 (0x34)
            Descriptor-data:
                 0000:  03 0a 4c 43 4e 20 4e 6f  72 77 61 79 4e 4f 52 24   ..LCN NorwayNOR$
                 0010:  1b a6 fc 11 1b ec fc 10  1b 99 fc 0a 04 0b fc 5d   ...............]
                 0020:  1b 9d fc 0b 04 0a fc 5c  1b a1 fc 05 42 b1 fd 2c   .......\....B..,
                 0030:  19 04 fc 12                                        ....

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 16 (0x10)
            Descriptor-data:
                 0000:  04 0a 4c 43 4e 20 53 77  65 64 65 6e 53 57 45 00   ..LCN SwedenSWE.


    Transport_stream_ID: 69 (0x0045)
    Original_network_ID: 70 (0x0046)  [= 1 degree W | Telenor]
    reserved_1: 15 (0x0f)
    Transport_descriptor_length: 123 (0x007b)

            DVB-DescriptorTag: 67 (0x43)  [= satellite_delivery_system_descriptor]
            descriptor_length: 11 (0x0b)
            Frequency: 17367808 (=  10.90300 GHz)
            Orbital_position: 16 (=   1.0)
            West_East_flag: 0 (0x00)  [= WEST]
            Polarisation: 1 (0x01)  [= linear - vertical]
            Kind: 1 (0x01)  [= DVB-S2]
            Roll Off Faktor: 1 (0x01)  [= Alpha 0.25]
            Modulation_type: 2 (0x02)  [= 8PSK]
            Symbol_rate: 2424832 (=  25.0000)
            FEC_inner: 3 (0x03)  [= 3/4 conv. code rate]

            DVB-DescriptorTag: 65 (0x41)  [= service_list_descriptor]
            descriptor_length: 6 (0x06)
               service_ID: 7119 (0x1bcf)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]

               service_ID: 7382 (0x1cd6)[ --> refers to PMT program_number]
               service_type: 25 (0x19)  [= advanced codec HD digital television service]


            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 21 (0x15)
            Descriptor-data:
                 0000:  01 0b 4c 43 4e 20 44 65  6e 6d 61 72 6b 44 4e 4b   ..LCN DenmarkDNK
                 0010:  04 1b cf fc 09                                     .....

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 17 (0x11)
            Descriptor-data:
                 0000:  02 0b 4c 43 4e 20 46 69  6e 6c 61 6e 64 46 49 4e   ..LCN FinlandFIN
                 0010:  00                                                 .

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 16 (0x10)
            Descriptor-data:
                 0000:  03 0a 4c 43 4e 20 4e 6f  72 77 61 79 4e 4f 52 00   ..LCN NorwayNOR.

            DVB-DescriptorTag: 95 (0x5f)  [= private_data_specifier_descriptor]
            descriptor_length: 4 (0x04)
            PrivateDataSpecifier: 41 (0x00000029)  [= NorDig �]

            DVB-DescriptorTag: 135 (0x87)  [= User defined/ATSC reserved]
            descriptor_length: 16 (0x10)
            Descriptor-data:
                 0000:  04 0a 4c 43 4e 20 53 77  65 64 65 6e 53 57 45 00   ..LCN SwedenSWE.

CRC: 2016660374 (0x7833cb96)

```



but dvbsnoop -s pidscan doesn't return anything.


```
root@vuzero:~# dvbsnoop -s pidscan
dvbsnoop V1.4.53 -- https://github.com/PLi-metas/dvbsnoop 

---------------------------------------------------------
Transponder PID-Scan...
---------------------------------------------------------
root@vuzero:~# 
```


@Huevos Is there anything I can do to make it successfully do a pidscan on vu+ zero (BH 3.0.8C) ?
